### ISSUE TITLE
Package versions etc

### ISSUE THREAD

**Issue by mdogucu** [bayes-bats/tier2-freq-bayes#3]
I am currently reading the public policy paper. I realize that R is cited. It would be best to also track which packages (and their versions) are used to create the teaching materials etc. 

The full list can be found using the `sessionInfo()` function. See an example in [one of my slides](https://stats6-wi24.github.io/slides/week04/4b-reproducible-workflow.html#/section-4). You would need to scroll down to see the full list. 

When you have the session information added to the repo, can you also please include this in the README.md that the session info is available. 

- [ ] Add session info
- [ ] Add session info availability to `README.md`
- [ ] Add session info availability to the manuscript

**Comment by zdelrosario** [comment]
Added session info and linked in README and JOSE manuscript (https://github.com/bayes-bats/tier2-freq-bayes/commit/a5982cf068a642029056d033dc3429f5e5cf6a6f)
